version: "3"

services:
  bevy:
    build: .
    command: sleep infinity
    tty: true
    volumes:
      - ../:/bevy
      - ~/.gitconfig:/home/vscode/.gitconfig
    environment:
      SHELL: /usr/bin/zsh
